name: Auto Push and Release (Drupal-Payment)

on:
  push:
    branches:
      - drupal-payment  # Trigger workflow only when this branch is updated

jobs:
  update-main:
    name: Sync Drupal-Payment to Master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Ensure Master Branch Exists
        run: |
          if git ls-remote --heads origin master | grep master; then
            echo "Master branch exists."
          else
            echo "Creating master branch."
            git checkout -b master
            git push origin master
          fi

      - name: Merge changes into master
        run: |
          git checkout master
          git merge --no-edit --strategy-option=theirs drupal-payment || exit 0
          git push origin master

  release:
    name: Create Release
    needs: update-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version number
        id: get_version
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: false
